#!/usr/bin/env python3
import platform
import webbrowser
import subprocess
from tkinter import filedialog
from tkinter import *


global prefix
os_name = platform.system()
if os_name == "Windows":
    wrapper_command = ["python"]
    prefix = "./scripts/"
else:
    wrapper_command = []
    prefix = ""


def main():
    main_window = Tk()
    main_window.geometry("500x500")
    main_window.config(background="white")

    title_frame = Frame(main_window, background="#D2E2FB", bd=1, relief="flat")
    title_frame.pack()

    title = Label(
        title_frame,
        text="CPM Extractor",
        width=50,
        height=4,
        fg="black",
        font="50",
    )
    title.config(background="white")
    title.pack()

    def select_input(label):
        def run_and_forget(cmd_line, button_run):
            try:
                subprocess.run(cmd_line)
            except Exception as e:
                button_run.forget()
                raise (e)

        input_file = filedialog.askopenfilename(
            initialdir="./",
            title="Select a File",
            filetypes=(("KML files", "*.kml*"), ("all files", "*.*")),
        )
        label.configure(text=f"File Opened: {input_file}")

        if input_file != ():
            entry_col = Entry(main_window, width=50)

            entry_col.insert(END, "CPM column (case-sensitive)")

            entry_col.pack()

            button_run = Button(main_window, text="RUN")

            button_run.config(
                command=lambda cmd_line=wrapper_command + [
                    f"{prefix}CPM_extractor",
                    "--input",
                    input_file,
                    "--column",
                    entry_col.get(),
                ]: run_and_forget(cmd_line, button_run),
            )
            button_run.pack(side="top")

    FE_frame = Frame(main_window)

    label_file_explorer = Label(FE_frame, text="File Opened: ", fg="blue")

    button_explore = Button(
        FE_frame,
        text="Input File",
        command=lambda label=label_file_explorer: select_input(label),
    )
    FE_frame.pack(side="top")
    button_explore.pack(side="left")
    label_file_explorer.pack(side="left")

    button_exit = Button(main_window, text="Exit", command=exit)
    button_exit.pack(side="bottom")

    main_window.mainloop()


if __name__ == "__main__":
    main()
